### ISSUE TITLE
TypeError: GSI.on is not a function

### ISSUE THREAD

**Issue by borzaka** [osztenkurden/csgogsi-socket#22]
I can't make this package working, I have followed the example.
If I use `socket.io-client` instead, it works. What am I missing?

I have a React TypeScript Vite project.

With `csgogsi-socket`, it throws a `TypeError: GSI.on is not a function` error:
```js
import { GSISocket } from 'csgogsi-socket';

const GSI = GSISocket('localhost:5173', 'update');

GSI.on('roundEnd', team => {
    console.log(`Team ${team.name} win!`);
});
```

With `socket.io-client` and `csgogsi` it's working:
```js
import { io } from "socket.io-client";
import { CSGO, CSGOGSI } from 'csgogsi';

const GSI = new CSGOGSI();
const socket = io('localhost:5173');

socket.on("update", (data: any) => {
    GSI.digest(data);
});

GSI.on('roundEnd', team => {
    console.log(`Team ${team.winner.name} win!`);
});
```

**Comment by osztenkurden** [comment]
This package will be slowly being deprecated. As used in cs2-react-hud, I'd advise on going with the second solution, using only csgogsi.
